import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import {motionAt} from '../dist/motion-math.mjs';import {GIFEncoder,quantize,applyPalette} from '../dist/vendor/gifenc.mjs';
const dir='dist/';const context={};vm.createContext(context);vm.runInContext(fs.readFileSync(dir+'catalog.js','utf8'),context);vm.runInContext(fs.readFileSync(dir+'meaning.js','utf8'),context);const prefix=fs.readFileSync(dir+'app.js','utf8').split('const special=')[0];vm.runInContext(prefix+';globalThis.testKit=kit;',context);const {MischiefMeaning:meaning,testKit:allKit}=context;const kit=allKit.slice(0,32);assert.equal(context.MischiefCatalog.count,3953);assert.equal(new Set(allKit.map(x=>x.emoji)).size,3953);for(const item of context.MischiefCatalog.items)assert.ok(allKit.some(x=>x.emoji===item.emoji));
assert.equal(meaning([kit[0],kit[4]]).title,'Happy and hurting');assert.equal(meaning([kit[12],kit[13]]).title,'Love, turned up');assert.equal(meaning([kit[0],kit[13]],'comfort').title,"I'm here with you");assert.equal(meaning([kit[0],kit[13]],'comfort','Proud of you').title,'Proud of you');assert.equal(meaning([kit[0],kit[13]],'auto','x'.repeat(200)).title.length,140);
for(let a=0;a<kit.length;a++)for(let b=0;b<kit.length;b++)for(let c=0;c<kit.length;c++){const m=meaning([kit[a],kit[b],kit[c]]);assert.ok(m.title&&m.description&&m.alt);assert.equal(m.traits.length,3);}
for(let n=0;n<500;n++){const m=meaning([kit[n%32],kit[(n*3)%32],kit[(n*7)%32],kit[(n*11)%32]]);assert.equal(m.traits.length,4);}
for(const type of ['bounce','heartbeat','wiggle','float']){const a=motionAt(type,0),b=motionAt(type,1);for(const key in a)assert.ok(Math.abs(a[key]-b[key])<1e-9,'loop must close');}
const gif=GIFEncoder();for(let f=0;f<25;f++){const rgba=new Uint8ClampedArray(16*16*4);for(let i=0;i<256;i++){rgba[i*4]=f*10;rgba[i*4+1]=220;rgba[i*4+2]=50;rgba[i*4+3]=i%16<8?255:0;}const colors=quantize(rgba,255,{format:'rgb565'});const index=applyPalette(rgba,colors,'rgb565');for(let i=0;i<index.length;i++)index[i]=rgba[i*4+3]<128?0:index[i]+1;gif.writeFrame(index,16,16,{palette:[[0,0,0],...colors],delay:80,repeat:0,transparent:true,transparentIndex:0,dispose:2});}gif.finish();const data=gif.bytes();assert.equal(Buffer.from(data.subarray(0,6)).toString(),'GIF89a');assert.equal(data.at(-1),0x3b);
let p=13,frames=0,controls=0;if(data[10]&128)p+=3*(2**((data[10]&7)+1));function blocks(){while(data[p])p+=data[p]+1;p++;}while(data[p]!==0x3b){if(data[p]===0x21){if(data[p+1]===0xf9){assert.equal((data[p+3]>>2)&7,2);assert.equal(data[p+3]&1,1);controls++;}p+=2;blocks();}else if(data[p]===0x2c){frames++;const flags=data[p+9];p+=10;if(flags&128)p+=3*(2**((flags&7)+1));p++;blocks();}else throw Error('Invalid GIF block '+p);}assert.equal(frames,25);assert.equal(controls,25);
for(const file of ['index.html','integration.html','integration-demo.html']){const html=fs.readFileSync(dir+file,'utf8');for(const match of html.matchAll(/(?:src|href)="([^"#]+)"/g)){const ref=match[1].split('?')[0];if(/^https?:|^data:/.test(ref)||ref==='./')continue;assert.ok(fs.existsSync(dir+ref),file+' missing '+ref);}}
console.log('PASS: semantic rules, 32,768 three-ingredient mixes, 500 four-ingredient mixes, intention override, caption bounds, closed animation loops, 25 GIF frames with transparency/disposal, HTML asset references.');
