import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';const c={};vm.createContext(c);for(const file of ['catalog.js','composition.js','meaning.js'])vm.runInContext(fs.readFileSync('dist/'+file,'utf8'),c);const get=emoji=>c.MischiefCatalog.items.find(x=>x.emoji===emoji);const p=c.MischiefComposition.plan.bind(c.MischiefComposition);
for(const emoji of ['🤔','😊','😭','😡','❤️','🐱','🍕'])for(const order of [[get(emoji),get('👑')],[get('👑'),get(emoji)]]){assert.equal(p(order).base.emoji,emoji);assert.equal(p(order).effects.crown,true);assert.equal(p(order).accents.length,0);}
for(const emoji of ['🤔','😊','😭','😡','❤️','🐱','🍕'])for(const order of [[get(emoji),get('❄️')],[get('❄️'),get(emoji)]]){assert.equal(p(order).base.emoji,emoji);assert.equal(p(order).effects.frozen,true);assert.equal(p(order).accents.length,0);}
const multi=p([get('👑'),get('❄️'),get('🤔'),get('✨')]);assert.equal(multi.base.emoji,'🤔');assert.ok(multi.effects.crown&&multi.effects.frozen&&multi.effects.sparkle);assert.equal(multi.accents.length,0);
// Exercise the actual renderer at export resolution with a recording canvas context.
const calls=[];function canvas(size=1024){const ctx=new Proxy({measureText:()=>({width:280}),createLinearGradient:()=>({addColorStop(){}})}, {get(o,k){return o[k]||((...args)=>{assert.ok(args.every(a=>typeof a!=='number'||Number.isFinite(a)));calls.push([k,...args]);});},set(o,k,v){if(k==='font')assert.match(v,/^[0-9.]+px /);o[k]=v;return true;}});return {width:size,height:size,getContext:()=>ctx};}c.document={createElement:()=>canvas()};c.MischiefComposition.draw(canvas(),[get('👑'),get('❄️'),get('🤔'),get('✨')]);assert.ok(!calls.some(x=>x[0]==='fillText'&&x[1]==='👑'),'Crown must be fitted geometry, not an overlaid emoji');assert.ok(calls.some(x=>x[0]==='bezierCurveTo'));assert.ok(calls.some(x=>x[0]==='fillText'&&x[1]==='❄️'));assert.ok(calls.some(x=>x[0]==='fillText'&&x[1]==='🤔'));assert.ok(calls.some(x=>x[0]==='fillRect'));
console.log('PASS: crown and freezing rules in either order, seven subjects, combined crown/frost/sparkles, renderer call path at 1024px.');

for(const emoji of ['🤔','😊','😭','😡','❤️','🐱','🍕'])for(const rain of ['🌧️','🌦️','☔','💦'])for(const order of [[get(emoji),get(rain)],[get(rain),get(emoji)]]){assert.equal(p(order).base.emoji,emoji);assert.equal(p(order).effects.rain,true);assert.equal(p(order).accents.length,0);}
c.MischiefComposition.draw(canvas(),[get('🤔'),get('🌧️')]);console.log('PASS: rain transformations in either order, seven subjects and four water modifiers.');

for(const [a,b,result] of [['❤️','🔥','❤️‍🔥'],['😊','❤️','🥰'],['😊','💋','😘'],['😊','😭','🥲']])for(const pair of [[a,b],[b,a]]){const plan=p(pair.map(get));assert.equal(plan.renderEmoji,result);assert.equal(plan.accents.length,0);for(const phase of [0,.25,.5,.75,1])c.MischiefComposition.draw(canvas(),pair.map(get),phase);}
assert.equal(p([get('😊'),get('😊')]).accents.length,0);
